import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {getWaveX,getWaveY} from '../hero-scroll.mjs';
import {createRenderSizeSync} from '../scene-runtime.mjs';
const source=readFileSync(new URL('../script.js',import.meta.url),'utf8');
const xExpression=source.match(/float x = (mix\(-4\.2[^;]+);/)[1];
function actualShaderX(t,aSeed){return vm.runInNewContext(xExpression,{t,aSeed,mix:(a,b,t)=>a+(b-a)*t});}
test('actual shader ribbon remains wider than viewport at every flight position',()=>{for(const t of [0,.1,.25,.5,.75,.9,1]){const xs=Array.from({length:1001},(_,i)=>actualShaderX(t,i/1000));assert.ok(Math.max(...xs)-Math.min(...xs)>2.79);assert.ok(Math.abs(actualShaderX(t,.32)-getWaveX(t,.32))<1e-12);}assert.ok(actualShaderX(0,1)<-1);assert.ok(actualShaderX(1,0)>1);});
test('portrait projection keeps broad wave and seven separated lanes',()=>{for(const width of [315,390,945]){const height=844,slopeY=Math.tan(18*Math.PI/180),slopeX=slopeY*width/height,depth=8.7;const projected=Array.from({length:1000},(_,i)=>{const x=getWaveX(.5,i/999);const cameraX=x*slopeX*depth;return (cameraX/(slopeX*depth)+1)*width/2;});assert.ok(Math.max(...projected)-Math.min(...projected)>width*1.39);}const ys=Array.from({length:1000},(_,i)=>getWaveY(.5,i/999,.7));assert.ok(Math.max(...ys)-Math.min(...ys)>.5);});
test('flight updates uniforms without organic loops or position upload',()=>{const a=source.indexOf('function updateParticles('),b=source.indexOf('function setSceneMode',a);let uploads=0;const context={entranceMotion:true,introStartTime:0,INTRO_DURATION:5.2,scrollScatterTarget:1,flyThroughTarget:.5,pageFlowProgress:.6,compactLayout:true,material:{uniforms:Object.fromEntries(['uScrollExit','uFlyThrough','uPageProgress','uArrivalTime'].map(k=>[k,{value:0}]))},heroStage:{},sceneWrap:{},geometry:{attributes:{position:{set needsUpdate(v){uploads++;}}}},setSceneStyle(){},smooth01:x=>x*x*(3-2*x),clamp01:x=>Math.min(1,Math.max(0,x))};vm.runInNewContext(source.slice(a,b)+';updateParticles(.016,8)',context);assert.equal(context.material.uniforms.uFlyThrough.value,.5);assert.equal(context.material.uniforms.uArrivalTime.value,-1);assert.equal(uploads,0);});
test('stable canvas size avoids resize when browser chrome changes',()=>{let allocations=0;const canvas={clientWidth:390,clientHeight:744,width:0,height:0};const gl={isContextLost:()=>false,drawingBufferWidth:0,drawingBufferHeight:0};const renderer={getContext:()=>gl,setDrawingBufferSize(w,h,r){allocations++;canvas.width=gl.drawingBufferWidth=Math.floor(w*r);canvas.height=gl.drawingBufferHeight=Math.floor(h*r);}};const resize=createRenderSizeSync(renderer,canvas,()=>{},()=>1.5);resize();for(const innerHeight of [744,800,844,800,744]){void innerHeight;resize();}assert.equal(allocations,1);assert.equal(canvas.width,585);});
test('copy scroll exit does not add vertical movement or CSS catch-up transition',()=>{assert.match(source,/const copyY = 64 - revealProgress \* 64;/);assert.doesNotMatch(source,/copyExit \* 140/);const css=readFileSync(new URL('../style.css',import.meta.url),'utf8');assert.match(css.match(/\.hero-copy\s*\{([^}]+)\}/)[1],/transition: none/);});
