import test from 'node:test';import assert from 'node:assert/strict';
import {createParticleDrift,DRIFT_LIMIT,DRIFT_MAX_SPEED} from '../particle-drift.mjs';
import {stepRevealSpring} from '../scroll-spring.mjs';
function create(n=128){const seeds=Float32Array.from({length:n},(_,i)=>((i*618.033)%1000)/1000),base=Float32Array.from({length:n},(_,i)=>((i%8)/7-.5)*.18);return createParticleDrift(seeds,base);}
test('sharp scroll spreads particles independently with finite local energy',()=>{const d=create();d.step(1/60,.5);for(let k=0;k<8;k++)d.step(1/60,.5);const distances=[];for(let i=0;i<d.offsets.length;i+=2)distances.push(Math.hypot(d.offsets[i],d.offsets[i+1]));assert.ok(Math.max(...distances)>.06);assert.ok(new Set(distances.map(x=>x.toFixed(4))).size>80);assert.ok(Math.max(...d.velocity.map(Math.abs))<=DRIFT_MAX_SPEED+1e-6);});
test('pause relaxes individual springs; no perpetual flying or global synchronization',()=>{const d=create();d.step(1/60,.6);for(let i=0;i<600;i++)d.step(1/60,.6);assert.ok(Math.max(...d.velocity.map(Math.abs))<.001);assert.ok(Math.max(...d.offsets.map(Math.abs))<.015);const before=Array.from(d.offsets);assert.equal(d.step(1/60,.6),false);assert.deepEqual(Array.from(d.offsets),before);});
test('repeated jerks, reverse, huge dt and invalid inputs stay bounded',()=>{const d=create();for(let i=0;i<1800;i++){const target=i%80<40?.85:.15;d.step(i%33===0?100:1/60,target);for(const x of d.offsets){assert.ok(Number.isFinite(x));assert.ok(Math.abs(x)<=DRIFT_LIMIT+1e-6);}for(const v of d.velocity)assert.ok(Math.abs(v)<=DRIFT_MAX_SPEED+1e-6);}d.step(NaN,NaN);d.step(1/60,.8,true,true);assert.ok(d.offsets.every(x=>x===0));assert.ok(d.velocity.every(x=>x===0));});
test('slow scroll gives less scatter than a sudden displacement',()=>{const fast=create(),slow=create();fast.step(1/60,.6);for(let i=0;i<6;i++)fast.step(1/60,.6);for(let i=1;i<=120;i++)slow.step(1/60,.6*i/120);const energy=d=>d.offsets.reduce((sum,x)=>sum+x*x,0);assert.ok(energy(fast)>energy(slow)*4);});
test('hero reveal has bounded delayed response and stable reversal',()=>{let s={value:0,velocity:0};s=stepRevealSpring(s,1,1/60);assert.ok(s.value<.03);for(let i=0;i<10;i++)s=stepRevealSpring(s,1,1/60);assert.ok(s.value<.5);for(let i=0;i<600;i++){s=stepRevealSpring(s,i<200?1:i<400?0:1,i%51===0?20:1/60);assert.ok(s.value>=0&&s.value<=1);assert.ok(Math.abs(s.velocity)<=1.8);}assert.ok(s.value>.999);assert.deepEqual(stepRevealSpring(s,1,1,true),{value:1,velocity:0});});
